import { workflow } from "./helpers.js";

/**
 * Product and experience workflows.
 *
 * The onboarding capability expands into typed ONB-00 through ONB-22 catalog nodes so the
 * durable engine can schedule, checkpoint, retry, resume, and verify the nested graph. Only
 * ONB-22 writes the canonical onboarding artifacts, preserving the catalog's single-writer rule.
 */
const onboardingGraphWorkflows = [
  workflow({
    id: "workflow.experience.onboarding-system.onb-00-resume-scope",
    title: "Onboarding ONB-00: resume and classify scope",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Consumer onboarding work begins or resumes; classify greenfield, replacement, audit-only, or explicitly bounded incremental mode",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.data.analytics-and-attribution-blueprint", "workflow.experience.11-star-experience"],
    outputPaths: ["product/onboarding/graph/ONB-00-resume-scope.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-01-current-state-trace",
    title: "Onboarding ONB-01: current-state trace",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Trace the actual onboarding implementation, documents, routes, state, providers, events, failures, tests, and legacy surfaces",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-00-resume-scope"],
    outputPaths: ["product/onboarding/graph/ONB-01-current-state-trace.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-02-evidence-plan",
    title: "Onboarding ONB-02: evidence plan",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define the onboarding evidence hierarchy, access constraints, sample plan, and freshness cutoff",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-01-current-state-trace"],
    outputPaths: ["product/onboarding/graph/ONB-02-evidence-plan.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-03-current-guidance",
    title: "Onboarding ONB-03: current guidance research",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Research current consumer onboarding evidence, platform guidance, benchmarks, and practitioner heuristics",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    outputPaths: ["product/onboarding/graph/ONB-03-current-guidance.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-04-competitor-reviews",
    title: "Onboarding ONB-04: competitor review analysis",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Mine direct and adjacent competitor reviews, including negative themes and a positive-review control",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    outputPaths: ["product/onboarding/graph/ONB-04-competitor-reviews.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-05-onbo-hub-atlas",
    title: "Onboarding ONB-05: authorized flow atlas",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Build an authorized Onbo Hub flow atlas without scraping, bypassing access controls, or inferring locked screens",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    outputPaths: ["product/onboarding/graph/ONB-05-onbo-hub-atlas.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-06-internal-guidance-audit",
    title: "Onboarding ONB-06: internal guidance audit",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Audit applicable Formation and internal B2C guidance and resolve conflicts or outdated rules",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    outputPaths: ["product/onboarding/graph/ONB-06-internal-guidance-audit.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-07-provider-policy-landscape",
    title: "Onboarding ONB-07: provider and policy landscape",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Refresh monetization, identity, analytics, RevenueCat, billing, platform-policy, and regional capability facts",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    providers: ["provider.revenuecat", "provider.posthog", "provider.app-store-connect", "provider.google-play"],
    outputPaths: ["product/onboarding/graph/ONB-07-provider-policy-landscape.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-08-motion-research",
    title: "Onboarding ONB-08: motion research",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Research interaction and motion references with 60fps and translate them into the target framework",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-02-evidence-plan"],
    outputPaths: ["product/onboarding/graph/ONB-08-motion-research.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-09-evidence-join",
    title: "Onboarding ONB-09: evidence join",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Join guidance, reviews, flow evidence, internal doctrine, provider facts, policy, and motion research into explicit decisions",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: [
      "workflow.experience.onboarding-system.onb-03-current-guidance",
      "workflow.experience.onboarding-system.onb-04-competitor-reviews",
      "workflow.experience.onboarding-system.onb-05-onbo-hub-atlas",
      "workflow.experience.onboarding-system.onb-06-internal-guidance-audit",
      "workflow.experience.onboarding-system.onb-07-provider-policy-landscape",
      "workflow.experience.onboarding-system.onb-08-motion-research",
    ],
    outputPaths: ["product/onboarding/graph/ONB-09-evidence-join.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-10-first-value-activation",
    title: "Onboarding ONB-10: first value and activation",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define first value rendered, first value engaged, activation, habit, and retention hypotheses",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-09-evidence-join"],
    outputPaths: ["product/onboarding/graph/ONB-10-first-value-activation.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-11-effort-question-audit",
    title: "Onboarding ONB-11: effort and question audit",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Audit effort before value, question usefulness, permissions, interruption budget, and visible personalization proof",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-09-evidence-join"],
    outputPaths: ["product/onboarding/graph/ONB-11-effort-question-audit.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-12-state-identity-contract",
    title: "Onboarding ONB-12: state and identity contract",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define canonical journey, profile, identity, entitlement, continuity, and cross-surface state transitions",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-09-evidence-join"],
    providers: ["provider.revenuecat"],
    outputPaths: ["product/onboarding/graph/ONB-12-state-identity-contract.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-13-analytics-experiments",
    title: "Onboarding ONB-13: analytics and experiments",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define typed analytics, authoritative emitters, identity stitching, deduplication, experiment assignment, exposure, and expected sequences",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-09-evidence-join"],
    providers: ["provider.posthog", "provider.revenuecat"],
    outputPaths: ["product/onboarding/graph/ONB-13-analytics-experiments.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-14-trust-lifecycle-policy",
    title: "Onboarding ONB-14: trust, lifecycle, and policy",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define review timing, permissions, lifecycle, privacy, security, accessibility, and policy behavior",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.onboarding-system.onb-09-evidence-join"],
    outputPaths: ["product/onboarding/graph/ONB-14-trust-lifecycle-policy.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-15-architecture-decision",
    title: "Onboarding ONB-15: architecture decision",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Compare native-first, hosted-funnel-first, hybrid, web-first, and evidence-backed alternatives and select one target architecture",
    laneIds: ["onboarding"],
    phaseIds: ["phase.1c", "phase.2"],
    dependencies: [
      "workflow.experience.onboarding-system.onb-10-first-value-activation",
      "workflow.experience.onboarding-system.onb-11-effort-question-audit",
      "workflow.experience.onboarding-system.onb-12-state-identity-contract",
      "workflow.experience.onboarding-system.onb-13-analytics-experiments",
      "workflow.experience.onboarding-system.onb-14-trust-lifecycle-policy",
    ],
    outputPaths: ["product/onboarding/graph/ONB-15-architecture-decision.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-16-journey-graph",
    title: "Onboarding ONB-16: canonical journey graph",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define acquisition-specific journeys that converge on one semantic onboarding state graph",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.experience.onboarding-system.onb-15-architecture-decision"],
    outputPaths: ["product/onboarding/graph/ONB-16-journey-graph.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-17-screen-control-paywall-contract",
    title: "Onboarding ONB-17: screen, control, and paywall contract",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Specify every onboarding screen, copy key, control, action, paywall state, failure, recovery, accessibility, and localization behavior",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.experience.onboarding-system.onb-16-journey-graph"],
    providers: ["provider.revenuecat"],
    outputPaths: ["product/onboarding/graph/ONB-17-screen-control-paywall-contract.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-18-visual-design-prototype",
    title: "Onboarding ONB-18: visual design and prototype",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Produce actual high-fidelity onboarding design, motion, an interactive prototype, and design QA",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.experience.onboarding-system.onb-16-journey-graph"],
    outputPaths: ["product/onboarding/graph/ONB-18-visual-design-prototype.md"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-19-implementation-cutover-contract",
    title: "Onboarding ONB-19: implementation and cutover contract",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Define implementation units, reliability, performance, observability, privacy, migration, hard cutover, and deletion work",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2", "phase.5b"],
    dependencies: ["workflow.experience.onboarding-system.onb-16-journey-graph"],
    outputPaths: ["product/onboarding/graph/ONB-19-implementation-cutover-contract.md"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-20-adversarial-qa",
    title: "Onboarding ONB-20: adversarial QA",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Run the synthetic one-star pre-mortem, policy review, instrumentation QA, accessibility review, and provider-realism review",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2", "phase.5b"],
    dependencies: [
      "workflow.experience.onboarding-system.onb-17-screen-control-paywall-contract",
      "workflow.experience.onboarding-system.onb-18-visual-design-prototype",
      "workflow.experience.onboarding-system.onb-19-implementation-cutover-contract",
    ],
    outputPaths: ["product/onboarding/graph/ONB-20-adversarial-qa.md"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.onboarding-system.onb-21-compound-engineering-plan",
    title: "Onboarding ONB-21: Compound Engineering plan",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Translate the accepted onboarding graph into an implementation-ready Compound Engineering plan, or the Formation-equivalent fallback",
    laneIds: ["onboarding"],
    phaseIds: ["phase.5b"],
    dependencies: ["workflow.experience.onboarding-system.onb-20-adversarial-qa"],
    outputPaths: ["product/onboarding/graph/ONB-21-compound-engineering-plan.md"],
    actionClass: "draft",
    idempotent: true,
  }),
] as const;

export const workflows = [
  workflow({
    id: "workflow.product.app-archetype-detection-and-starter",
    title: "App-archetype detection & starter",
    domainId: "domain.product",
    areaIds: ["area.product-experience"],
    trigger: "Request matches a known product shape (social / AI-chat / habit / photo-AI)",
    laneIds: ["product"],
    gates: ["check:app-archetype", "check:archetype-starter"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.research.research-backed-spec",
    title: "Research-backed spec",
    domainId: "domain.research",
    areaIds: ["area.product-experience"],
    trigger: "Need category economics, competitor, review/social-language, keyword, or name-collision evidence",
    laneIds: ["research", "product"],
    phaseIds: ["phase.1"],
    outputPaths: ["strategy/RESEARCH.md", "product/SPEC.md"],
    gates: ["check:research"],
    founderOnlyActions: ["decide Go, Pivot, or Kill"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.research.localization-market-research",
    title: "Localization market research",
    domainId: "domain.research",
    areaIds: ["area.product-experience"],
    trigger: "Before localizing any surface or choosing locales",
    laneIds: ["research"],
    phaseIds: ["phase.1"],
    outputPaths: ["strategy/localization-market-research/LOCALIZATION_MARKET_RESEARCH.md"],
    providers: ["provider.aso-skills"],
    actionClass: "observe",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.11-star-experience",
    title: "11-star experience",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: '"11-star run" / before SPEC, onboarding, ads, store creative, or eng plans harden',
    laneIds: ["experience"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.research.research-backed-spec"],
    outputPaths: ["product/experience/11-star-experience/11_STAR_EXPERIENCE.md", "product/experience/11-star-experience/11-star-experience.html"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.emotional-experience-design-producer",
    title: "Emotional experience design (producer)",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: 'Feature whose 11-star target is 6★+ / "charge this with emotion", "build a habit"',
    laneIds: ["emotional_design"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.11-star-experience", "workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["product/experience/emotional-design/EMOTIONAL_DESIGN.md"],
    gates: ["check:emotional-design"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.experience.emotional-design-audit-auditor",
    title: "Emotional design audit (auditor)",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: '"Audit this app\'s emotional design" / "emotional UX audit"',
    laneIds: ["emotional_design"],
    phaseIds: ["phase.1c"],
    dependencies: ["workflow.experience.emotional-experience-design-producer"],
    outputPaths: ["product/experience/emotional-design/EMOTIONAL_AUDIT.md"],
    gates: ["check:emotional-design"],
    actionClass: "draft",
    idempotent: true,
  }),
  workflow({
    id: "workflow.design.design-room-state-mutate-version-render",
    title: "Design Room (state→mutate→version→render)",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Any design/visual-system/cross-surface/store-creative/landing/onboarding/paywall work",
    laneIds: ["design"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["studio/seed/business.json", "studio/seed/theme.tokens.json", "design/design-room.html"],
    gates: ["validate:design-state", "check:design-room", "render:design-room"],
    founderOnlyActions: ["approve final brand direction"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.design.token-promotion",
    title: "Token promotion",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Theme tokens change and the design is accepted",
    laneIds: ["design"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render"],
    outputPaths: ["studio/generated/system/tokens.json", "design/system/tokens.css", "studio/generated/system/DesignTokens.swift"],
    gates: ["check:token-promotion"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.design.ux-patterns-refero",
    title: "UX patterns (Refero)",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Before flow maps, state matrices, UX_PATTERNS.md, or bug-trap coverage",
    laneIds: ["design"],
    phaseIds: ["phase.2"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render"],
    outputPaths: ["product/experience/ux-patterns/UX_PATTERNS.md"],
    providers: ["provider.refero"],
    actionClass: "draft",
    idempotent: true,
  }),
  ...onboardingGraphWorkflows,
  workflow({
    id: "workflow.experience.onboarding-conversion",
    title: "Onboarding ONB-22: execute, cut over, and verify",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Implement or finalize the accepted onboarding graph, verify the canonical artifacts, cut over, and prove zero legacy",
    laneIds: ["onboarding"],
    phaseIds: ["phase.2", "phase.5b"],
    dependencies: ["workflow.experience.onboarding-system.onb-21-compound-engineering-plan"],
    outputPaths: ["product/ONBOARDING.md", "product/onboarding.html"],
    gates: ["check:onboarding-graph"],
    providers: ["provider.revenuecat", "provider.posthog"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.design.premium-mobile-craft",
    title: "Premium mobile craft",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: 'Before in-app UI build/polish, press-state/haptics/loading-empty wiring, or "premium feel"',
    laneIds: ["design"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render"],
    outputPaths: ["design/DESIGN.md"],
    gates: ["check:motion-contract"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.design.content-assets-remotion-generated-visuals",
    title: "Content assets / Remotion / generated visuals",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Before rendered videos/stills, app previews, ad/social variants",
    laneIds: ["content_assets"],
    phaseIds: ["phase.2", "phase.3"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render"],
    outputPaths: ["growth/content-assets/CONTENT_ASSETS.md", "growth/content-assets/content-assets.html"],
    gates: ["check:content-assets"],
    providers: ["provider.higgsfield"],
    actionClass: "mutate",
    idempotent: false,
  }),
  workflow({
    id: "workflow.words.writing-quality-no-slop",
    title: "Writing quality (no-slop)",
    domainId: "domain.words",
    areaIds: ["area.product-experience"],
    trigger: "Before writing or reviewing any founder-facing copy or any marketing copy the skill generates",
    outputPaths: ["product/copy/COPY_BRIEF.md", "product/copy/COPY_DECK.md"],
    gates: ["check:app-copy"],
    actionClass: "draft",
    idempotent: true,
  }),
] as const;
